# Dockerfile for testing the main image
# This extends the main Dockerfile to run tests

ARG BASE_IMAGE=rstats-dev:latest
FROM ${BASE_IMAGE}

# Copy test files
COPY tests/ /tests/
COPY rpackages.txt /tests/rpackages.txt

# Set working directory
WORKDIR /tests

# Run tests when container starts
CMD ["sh", "-c", "Rscript test_packages.R && Rscript test_cmdstanr.R"]